global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - alerts.yml

scrape_configs:
  - job_name: etl-app
    static_configs:
      - targets: ['cli-app:8000'] # Scrape the app metrics endpoint
  
  - job_name: postgres
    static_configs:
      - targets: ['postgres-exporter:9187'] # Scrape Postgres exporter metrics
  
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090'] # Scrape Prometheus's own metrics